name: Android
on: [push]

jobs:
  android:
    name: Android
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: |
          ./configure.sh

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk /opt/Android/sdk --ndk /opt/Android/ndk)

      - name: Compile
        shell: bash
        run: (cd android; ./gradlew bundleWebDebug packageWebDebugUniversalApk)

      - uses: actions/upload-artifact@v2
        with:
          name: android-universal-apk
          path: android/build/outputs/universal_apk/webDebug/android-web-debug-universal.apk
          if-no-files-found: error
