name: Check
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  android-check:
    name: Android Check
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
          clean: false # speed up builds

      - name: Remove old outputs
        shell: bash
        run: |
          rm -rf android/build/outputs/

      - name: Configure
        shell: bash
        run: |
          ./configure.sh

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk /opt/Android/sdk --ndk /opt/Android/ndk)

      - name: Compile
        shell: bash
        # Just check compilation for one architecture
        run: (cd android; ./gradlew -Parm64 bundleWebDebug)
