name: Check
on:
  push:
    branches:
      - '!master'

jobs:
  desktop-check:
    name: Desktop Check
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
          clean: false

      - name: Configure
        shell: bash
        run: |
          ./configure.sh

      - name: Compile
        shell: bash
        run: |
          (mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && make -j $(($(nproc)*2)))

#      - name: Test
#        shell: bash
#        run: ./tools/python/run_desktop_tests.py -f build/ -e generator_integration_tests,opening_hours_integration_tests,opening_hours_supported_features_tests,routing_consistency_tests,routing_integration_tests,routing_quality_tests,storage_integration_tests
